homepage: "https://github.com/GrokImageCompression/grok"
primary_contact: "boxerab@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - memory
  - undefined
  - dataflow
