homepage: "https://github.com/radare/radare2"
primary_contact: "pancake@nopcode.org"
auto_ccs:
  - "zlowram@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
run_tests: False
