homepage: "https://www.freedesktop.org/wiki/Software/kmscon/libtsm/"
primary_contact: "dh.herrmann@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
