homepage: "http://commonmark.org"
primary_contact: "jgm@berkeley.edu"
auto_ccs:
  - "kivikakk@github.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
