homepage: "https://libgit2.github.com/"
primary_contact: "ps@pks.im"
auto_ccs:
  - "nelhage@nelhage.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - undefined
