homepage: "http://svn.freebsd.org/base/head/sys/teken/"
primary_contact: "ed@nuxi.nl"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
