homepage: "https://developers.google.com/speed/webp/"
primary_contact: "jzern@google.com"
auto_ccs:
- pascal.massimino@gmail.com
- vrabaud@google.com
- yguyon@google.com
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
