homepage: "https://www.wolfssl.com/"
primary_contact: "jacob@wolfssl.com"
auto_ccs:
 - "david@wolfssl.com"
 - "kaleb@wolfssl.com"
 - "levi@wolfssl.com"
 - "testing@wolfssl.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory:
    experimental: True
  - undefined
