homepage: "https://github.com/kinetiknz/nestegg"
primary_contact: "mgregan@mozilla.com"
auto_ccs:
- "twsmith@mozilla.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
